name: lp_env
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - anyio=4.12.0
  - async-timeout=5.0.1
  - attrs=25.4.0
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.4
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.1
  - azure-identity-cpp=1.13.2
  - azure-storage-blobs-cpp=12.15.0
  - azure-storage-common-cpp=12.11.0
  - azure-storage-files-datalake-cpp=12.13.0
  - backports.zstd=1.2.0
  - binutils_impl_linux-64=2.45
  - binutils_linux-64=2.45
  - blas=2.304
  - blas-devel=3.11.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - cpython=3.10.19
  - cuda-cccl=12.9.27
  - cuda-cccl_linux-64=12.9.27
  - cuda-command-line-tools=12.1.1
  - cuda-compiler=12.9.0
  - cuda-crt-dev_linux-64=12.9.41
  - cuda-crt-tools=12.9.41
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cudart-dev_linux-64=12.9.79
  - cuda-cudart-static_linux-64=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-cuobjdump=12.9.26
  - cuda-cupti=12.1.105
  - cuda-cuxxfilt=12.9.19
  - cuda-documentation=12.4.127
  - cuda-driver-dev=12.9.79
  - cuda-driver-dev_linux-64=12.9.79
  - cuda-gdb=12.9.79
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.6.2
  - cuda-nsight=12.9.79
  - cuda-nvcc=12.9.41
  - cuda-nvcc-dev_linux-64=12.9.41
  - cuda-nvcc-impl=12.9.41
  - cuda-nvcc-tools=12.9.41
  - cuda-nvcc_linux-64=12.9.41
  - cuda-nvdisasm=12.9.88
  - cuda-nvml-dev=12.9.79
  - cuda-nvprof=12.9.79
  - cuda-nvprune=12.9.19
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-nvvm-dev_linux-64=12.9.41
  - cuda-nvvm-impl=12.9.41
  - cuda-nvvm-tools=12.9.41
  - cuda-nvvp=12.9.79
  - cuda-opencl=12.9.19
  - cuda-opencl-dev=12.9.19
  - cuda-profiler-api=12.9.79
  - cuda-sanitizer-api=12.9.79
  - cuda-toolkit=11.8.0
  - cuda-tools=12.1.1
  - cuda-version=12.9
  - cuda-visual-tools=12.6.2
  - datasets=4.4.1
  - dbus=1.16.2
  - dill=0.4.0
  - exceptiongroup=1.3.1
  - expat=2.7.3
  - filelock=3.20.0
  - fontconfig=2.15.0
  - freetype=2.14.1
  - frozenlist=1.7.0
  - fsspec=2025.10.0
  - gcc_impl_linux-64=13.4.0
  - gcc_linux-64=13.4.0
  - gds-tools=1.14.1.1
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gxx_impl_linux-64=13.4.0
  - gxx_linux-64=13.4.0
  - h11=0.16.0
  - h2=4.3.0
  - hf-xet=1.2.1
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - huggingface_hub=0.36.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - jinja2=3.1.6
  - kernel-headers_linux-64=4.18.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libabseil=20250512.1
  - libarrow=22.0.0
  - libarrow-acero=22.0.0
  - libarrow-compute=22.0.0
  - libarrow-dataset=22.0.0
  - libarrow-substrait=22.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcufile=1.14.1.1
  - libcufile-dev=1.14.1.1
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcurl=8.17.0
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-devel_linux-64=13.4.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.3
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnsl=2.0.1
  - libnvfatbin=12.9.82
  - libnvfatbin-dev=12.9.82
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=22.0.0
  - libpng=1.6.53
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsanitizer=13.4.0
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=13.4.0
  - libstdcxx-ng=15.2.0
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libutf8proc=2.11.2
  - libuuid=2.41.2
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.7
  - lz4-c=1.10.0
  - markupsafe=3.0.3
  - mkl=2025.3.0
  - mkl-devel=2025.3.0
  - mkl-include=2025.3.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.6.3
  - multiprocess=0.70.18
  - ncurses=6.5
  - networkx=3.4.2
  - nlohmann_json=3.12.0
  - nsight-compute=2025.2.1.3
  - nspr=4.38
  - nss=3.118
  - numpy=2.2.6
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openjpeg=2.5.4
  - openssl=3.6.0
  - optree=0.18.0
  - orc=2.2.1
  - pandas=2.3.3
  - pcre2=10.47
  - pip=25.3
  - prometheus-cpp=1.3.0
  - propcache=0.3.1
  - pthread-stubs=0.4
  - pyarrow=22.0.0
  - pyarrow-core=22.0.0
  - pybind11=3.0.1
  - pybind11-global=3.0.1
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-gil=3.10.19
  - python-tzdata=2025.2
  - python-xxhash=3.6.0
  - python_abi=3.10
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.3
  - re2=2025.11.05
  - readline=8.2
  - regex=2025.11.3
  - requests=2.32.5
  - s2n=1.6.2
  - safetensors=0.7.0
  - scipy=1.15.2
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - sympy=1.14.0
  - sysroot_linux-64=2.28
  - tbb=2022.3.0
  - tk=8.6.13
  - tokenizers=0.21.4
  - tqdm=4.67.1
  - transformers=4.52.4
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.6.1
  - wheel=0.45.1
  - xkeyboard-config=2.46
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.3
  - yaml=0.2.5
  - yarl=1.22.0
  - zlib=1.3.1
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - altair==6.0.0
      - aniposelib==0.7.2
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.1
      - astunparse==1.6.3
      - blinker==1.9.0
      - cachetools==6.2.2
      - choreographer==1.2.1
      - click==8.3.1
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - dm-tree==0.1.9
      - executing==2.2.1
      - fonttools==4.61.0
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.76.0
      - h5py==3.15.1
      - hydra-core==1.3.2
      - imagecorruptions-imaug==1.1.3
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - imaug==0.4.2
      - iniconfig==2.3.0
      - ipykernel==7.1.0
      - ipython==8.37.0
      - jedi==0.19.2
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.7.0
      - jupyter-core==5.9.1
      - kaleido==1.2.0
      - kiwisolver==1.4.9
      - kornia==0.8.2
      - kornia-rs==0.1.10
      - lazy-loader==0.4
      - lightning==2.6.0
      - lightning-pose==2.0.1
      - lightning-utilities==0.15.2
      - llvmlite==0.46.0
      - logistro==2.0.1
      - markdown==3.10
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - moviepy==2.2.1
      - narwhals==2.13.0
      - nest-asyncio==1.6.0
      - numba==0.63.0
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-dali-cuda110==1.50.0
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvcomp-cu11==5.0.0.6
      - nvidia-nvimgcodec-cu11==0.5.0.13
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvjpeg-cu11==11.9.0.86
      - nvidia-nvjpeg2k-cu11==0.9.0.43
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtiff-cu11==0.5.1.75
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - opencv-contrib-python==4.12.0.88
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - orjson==3.11.5
      - packaging==24.2
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.5.1
      - plotly==6.5.0
      - pluggy==1.6.0
      - proglog==0.1.12
      - prompt-toolkit==3.0.52
      - protobuf==6.33.2
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydeck==0.9.1
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pytest==9.0.2
      - pytest-timeout==2.4.0
      - python-dotenv==1.2.1
      - pytorch-lightning==2.6.0
      - pyzmq==27.1.0
      - referencing==0.37.0
      - rpds-py==0.30.0
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - seaborn==0.13.2
      - shapely==2.1.2
      - simplejson==3.20.2
      - smmap==5.0.2
      - stack-data==0.6.3
      - streamlit==1.52.1
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - toml==0.10.2
      - tomli==2.3.0
      - torch==2.9.1+cu126
      - torchmetrics==1.8.2
      - torchtyping==0.1.5
      - torchvision==0.24.1+cu126
      - tornado==6.5.2
      - traitlets==5.14.3
      - triton==3.5.1
      - typeguard==2.13.3
      - watchdog==6.0.0
      - wcwidth==0.2.14
      - werkzeug==3.1.4
      - wrapt==2.0.1
